# Generated by Django 6.0.3 on 2026-03-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
